### ISSUE TITLE
Regex fails if piped to |contains

### ISSUE THREAD

**Issue by joshnck** [SigmaHQ/pySigma-backend-crowdstrike#10]
https://github.com/SigmaHQ/pySigma-backend-crowdstrike/blob/1d673eabf9aeffa0ca826e01b6ce79d0451e9f72/sigma/pipelines/crowdstrike/crowdstrike.py#L443

I think this can be fixed with `(^[C-Z]:)|(\*[C-Z]:)` but I have not validated it yet.

**Comment by joshnck** [comment]
I'm also okay with this being closed as a non-issue because `c:\` should always be used with `|startswith`. Just something I noticed while doing some tuning.

**Comment by moullos** [comment]
Hi @joshnck 

This ended up highlighting some possible improvements to the backend so I ended up fixing it.

Thank you!
