### ISSUE TITLE
Curly brackets are not being escaped

### ISSUE THREAD

**Issue by xavigu42** [SigmaHQ/pySigma-backend-crowdstrike#15]
Hi guys,

Curly brackets are not being escaped and a couple of sigma rules are causing syntax errors.

Source:
https://github.com/SigmaHQ/pySigma-backend-crowdstrike/blob/1fdd29d5cac228687398769a09a8a4f68680b0b4/sigma/backends/crowdstrike/logscale.py#L127

Suggested fix:
```
add_escaped_re: ClassVar[str] = "*$^.|?()[]{}+/"
```

Affected sigma rules:
* https://github.com/SigmaHQ/sigma/blob/598d29f811c1859ba18e05b8c419cc94410c9a55/rules/windows/process_creation/proc_creation_win_hktl_relay_attacks_tools.yml#L47
* https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_iex_patterns.yml#L25

**Comment by moullos** [comment]
Thanks @xavigu42 

Easy fix as you suggested. Just merged #16 to fix.
